from classes_atv10 import*;

p1=Porta("Cinza","Alumínio",200,100)
p2=Porta("Marrom","Madeira",250,300)
p3=Porta("Branca","Ferro",300,200)
p4=Porta("Cinza","Aço",180,100)
p5=Porta("Branca","Madeira",220,125)
p6=Porta("Azul","Ferro",200,150)

c1=Casa("Centro",500,300)
c2=Casa("Zona rural",300,100)
c3=Casa("Zona sul",150,80)

c1.trocarPorta_frente(p1)
c1.trocarPorta_fundo(p2)
c1.fecharPorta_frente()
c1.trancarPorta_frente()
c1.fecharPorta_fundo()
c1.trancarPorta_fundo()
c1.destrancarPorta_fundo()
print(c1)

c2.trocarPorta_frente(p3)
c2.fecharPorta_frente()
c2.abrirPorta_frente()
c2.trocarPorta_fundo(p4)
c2.fecharPorta_fundo()
c2.trancarPorta_fundo()
print(c2)

c3.trocarPorta_frente(p5)
c3.abrirPorta_frente()
c3.trocarPorta_frente()
c3.abrirPorta_frente()
c3.fecharPorta_frente()
c3.trocarPorta_fundo(p6)
c3.trocarPorta_fundo()
c3.trocarPorta_fundo(p5)
c3.fecharPorta_fundo()
c3.trancarPorta_fundo()
c3.destrancarPorta_fundo()
print(c3)